# Generated by Django 4.2 on 2023-10-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
